runtime: nodejs16
env: standard
instance_class: F1
handlers:
  - url: .*
    script: auto
env_variables:
  NOTE_URL: https://api.followupboss.com/v1/notes
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: salesngage-social-posting@appspot.gserviceaccount.com